// Activity
export const FETCH_ACTIVITY = 'FETCH_ACTIVITY'
export const FETCH_ACTIVITY_SUCCESS = 'FETCH_ACTIVITY_SUCCESS'
export const REFRESH_ACTIVITY = 'REFRESH_ACTIVITY'

// Auth
export const ATTEMPT_APPLE_LOGIN = 'ATTEMPT_APPLE_LOGIN'
export const ATTEMPT_LOGIN = 'ATTEMPT_LOGIN'
export const ATTEMPT_LOGOUT = 'ATTEMPT_LOGOUT'
export const AUTH_APPLE = 'AUTH_APPLE'
export const AUTH_APPLE_SUCCESS = 'AUTH_APPLE_SUCCESS'
export const AUTH_EMAIL = 'AUTH_EMAIL'
export const AUTH_EMAIL_SUCCESS = 'AUTH_EMAIL_SUCCESS'
export const AUTH_REGISTER = 'AUTH_REGISTER'
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS'
export const FACEBOOK_AUTH = 'FACEBOOK_AUTH'
export const FACEBOOK_AUTH_SUCCESS = 'FACEBOOK_AUTH_SUCCESS'
export const GET_USER_BY_EMAIL = 'GET_USER_BY_EMAIL'
export const GET_USER_BY_EMAIL_SUCCESS = 'GET_USER_BY_EMAIL_SUCCESS'
export const LOGOUT = 'LOGOUT'
export const SET_AUTH_LOADING = 'SET_AUTH_LOADING'
export const SET_AUTH_USER = 'SET_AUTH_USER'
export const SET_LOGGED_IN = 'SET_LOGGED_IN'

// Business Detail
export const FETCH_BUSINESS_DETAILS = 'FETCH_BUSINESS_DETAILS'
export const FETCH_BUSINESS_DETAILS_SUCCESS = 'FETCH_BUSINESS_DETAILS_SUCCESS'
export const FETCH_LOCATION_DETAILS = 'FETCH_LOCATION_DETAILS'
export const FETCH_LOCATION_DETAILS_SUCCESS = 'FETCH_LOCATION_DETAILS_SUCCESS'
export const NAVIGATE_TO_BUSINESS_DETAIL = 'NAVIGATE_TO_BUSINESS_DETAIL'

// CreateProfile
export const CHECK_USERNAME = 'CHECK_USERNAME'
export const CHECK_USERNAME_SUCCESS = 'CHECK_USERNAME_SUCCESS'
export const CREATE_PROFILE = 'CREATE_PROFILE'
export const CREATE_PROFILE_SUCCESS = 'CREATE_PROFILE_SUCCESS'
export const SET_AVATAR = 'SET_AVATAR'
export const SET_SHOW_AVAILABLE_INDICATOR = 'SET_SHOW_AVAILABLE_INDICATOR'
export const SET_USERNAME = 'SET_USERNAME'

// Feed
export const FETCH_FEED = 'FETCH_FEED'
export const FETCH_FEED_SUCCESS = 'FETCH_FEED_SUCCESS'
export const REFRESH_FEED = 'REFRESH_FEED'
export const SET_FEED_TYPE = 'SET_FEED_TYPE'
export const SET_LOCATION_POSTS = 'SET_LOCATION_POSTS'
export const SET_POSTS = 'SET_POSTS'
export const SET_SHOULD_SCROLL_UP = 'SET_SHOULD_SCROLL_UP'

// Follow Tray
export const CLOSE_FOLLOWTRAY = 'CLOSE_FOLLOWTRAY'
export const SET_FOLLOWTRAY_USER = 'SET_FOLLOWTRAY_USER'

// Guess
export const ATTEMPT_GUESS = 'ATTEMPT_GUESS'
export const CREATE_GUESS = 'CREATE_GUESS'
export const CREATE_GUESS_SUCCESS = 'CREATE_GUESS_SUCCESS'
export const SET_GUESS_LOCATION = 'SET_GUESS_LOCATION'
export const SET_GUESS_POST_ID = 'SET_GUESS_POST_ID'
export const SET_GUESS_TEXT = 'SET_GUESS_TEXT'
export const SET_IS_GUESSING = 'SET_IS_GUESSING'
export const RESET_GUESS = 'RESET_GUESS'

// Leaderboard
export const FETCH_LEADERBOARD = 'FETCH_LEADERBOARD'
export const FETCH_LEADERBOARD_SUCCESS = 'FETCH_LEADERBOARD_SUCCESS'
export const REFRESH_LEADERBOARD = 'REFRESH_LEADERBOARD'

// My Posts
export const FETCH_MY_FEED = 'FETCH_MY_FEED'
export const FETCH_MY_FEED_SUCCESS = 'FETCH_MY_FEED_SUCCESS'
export const REFRESH_MY_FEED = 'REFRESH_MY_FEED'
export const SET_MY_POSTS = 'SET_MY_POSTS'

// Nav
export const SET_CURRENT_ROUTE_NAME = 'SET_CURRENT_ROUTE_NAME'

// Places
export const ASK_LOCATION_PERMISSION = 'ASK_LOCATION_PERMISSION'
export const CHECK_LOCATION = 'CHECK_LOCATION'
export const FETCH_PLACE = 'FETCH_PLACE'
export const FETCH_PLACE_SUCCESS = 'FETCH_PLACE_SUCCESS'
export const FETCH_PLACES = 'FETCH_PLACES'
export const FETCH_PLACES_SUCCESS = 'FETCH_PLACES_SUCCESS'
export const NO_LOCATION = 'NO_LOCATION'
export const PERMISSION_LOADING = 'PERMISSION_LOADING'
export const SELECT_PLACE = 'SELECT_PLACE'
export const SET_ASKED_LOCATION_PERMISSION = 'SET_ASKED_LOCATION_PERMISSION'
export const SET_CURRENT_LOCATION = 'SET_CURRENT_LOCATION'
export const SET_INCLUDE_NO_IDEA = 'SET_INCLUDE_NO_IDEA'
export const SET_PLACES = 'SET_PLACES'
export const SET_PLACES_SEARCH_STRING = 'SET_PLACES_SEARCH_STRING'
export const SET_SHOW_LOCATION_MODAL = 'SET_SHOW_LOCATION_MODAL'

// Post
export const CHEERS_POST = 'CHEERS_POST'
export const CHEERS_POST_SUCCESS = 'CHEERS_POST_SUCCESS'
export const CLEAR_CHEERS = 'CLEAR_CHEERS'
export const CREATE_COMMENT = 'CREATE_COMMENT'
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS'
export const CREATE_POST = 'CREATE_POST'
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'
export const DELETE_POST = 'DELETE_POST'
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'
export const FETCH_POST_CHEERS = 'FETCH_POST_CHEERS'
export const FETCH_POST_CHEERS_SUCCESS = 'FETCH_POST_CHEERS_SUCCESS'
export const FETCH_SINGLE_POST = 'FETCH_SINGLE_POST'
export const FETCH_SINGLE_POST_SUCCESS = 'FETCH_SINGLE_POST_SUCCESS'
export const REFRESH_DETAIL = 'REFRESH_DETAIL'
export const REPORT_POST = 'REPORT_POST'
export const REPORT_POST_SUCCESS = 'REPORT_POST_SUCCESS'
export const SET_IS_CREATING_POST = 'SET_IS_CREATING_POST'
export const SET_POST_CAPTION = 'SET_POST_CAPTION'
export const SET_POST_IMAGE = 'SET_POST_IMAGE'
export const SET_POST_IMAGE_URI = 'SET_POST_IMAGE_URI'
export const SET_POST_IMAGE_UPLOAD_PROGRESS = 'SET_POST_IMAGE_UPLOAD_PROGRESS'
export const SET_POST_LOCATION = 'SET_POST_LOCATION'

// Rewards
export const FETCH_REDEMPTIONS = 'FETCH_REDEMPTIONS'
export const FETCH_REDEMPTIONS_SUCCESS = 'FETCH_REDEMPTIONS_SUCCESS'
export const FETCH_REWARDS = 'FETCH_REWARDS'
export const FETCH_REWARDS_SUCCESS = 'FETCH_REWARDS_SUCCESS'
export const REDEEM_REWARD = 'REDEEM_REWARD'
export const REDEEM_REWARD_SUCCESS = 'REDEEM_REWARD_SUCCESS'

// UI
export const ASK_NOTIFICATION_PERMISSION = 'ASK_NOTIFICATION_PERMISSION'
export const CAUGHT_ERROR = 'CAUGHT_ERROR'
export const SET_LOADING = 'SET_LOADING'
export const SET_SHOW_NOTIFICATION_MODAL = 'SET_SHOW_NOTIFICATION_MODAL'
export const UPDATE_LOADING = 'UPDATE_LOADING'

// User
export const BLOCK_USER = 'BLOCK_USER'
export const BLOCK_USER_SUCCESS = 'BLOCK_USER_SUCCESS'
export const CREATE_USER = 'CREATE_USER'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const FETCH_BLOCKED = 'FETCH_BLOCKED'
export const FETCH_BLOCKED_SUCCESS = 'FETCH_BLOCKED_SUCCESS'
export const FETCH_MY_USER = 'FETCH_MY_USER'
export const FETCH_MY_USER_SUCCESS = 'FETCH_MY_USER_SUCCESS'
export const FOLLOW_USER = 'FOLLOW_USER'
export const FOLLOW_USER_SUCCESS = 'FOLLOW_USER_SUCCESS'
export const REFRESH_USER = 'REFRESH_USER'
export const RESET_DROPDOWN_DATA = 'RESET_DROPDOWN_DATA'
export const SET_DROPDOWN_DATA = 'SET_DROPDOWN_DATA'
export const UPDATE_USER = 'UPDATE_USER'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
